import './globals.css'
import { Poppins, Roboto } from 'next/font/google'   //Arimo,
import 'bootstrap/dist/css/bootstrap.min.css';
// import Header from './components/Header';
import Header2 from './components/Header2';
import Footer from './components/Footer';
import Whatsapp from './components/Whatsapp';
import Head from 'next/head';
import Script from 'next/script';
import Providers from './components/Providers';

// If loading a variable font, you don't need to specify the font weight
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable:"--primary-font",
  weight: ['100','200','300','400','500','600','700','800','900']
});
const roboto = Roboto({
  weight: ['100','300','400','500','700','900'], //['300','400','500'],
  subsets: ['latin'],
  display: 'swap', 
  variable:"--secondary-font",
});

export const metadata = {
  metadataBase: new URL("https://www.remlextech.com"),
  title: {
    default: 'Welcome Remlex Tech',
    template: `%s | Welcome Remlex Tech`
  },
  description: 'Generated by create next app',
  verification: {
    google: "google-site-verification=<Enter-the-number-here>"
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        {/* Bootstrap css */}
        <Head>
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
        </Head>
        {/* End of Head  */}
        <Providers>
          <Header2 />

          <Whatsapp />
          
          {children}
        
          <Footer />
        </Providers>

        {/* Bootstrap Js */}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></Script>
      </body>
    </html>
  )
}
